import React from 'react';
import { QRCodeCanvas } from 'qrcode.react';
import { Link } from 'react-router-dom'; // Import Link for navigation
import '../css/QRCode.css';
// Import icons (assuming react-icons is installed)
import { FaDownload, FaHome, FaUserCircle, FaCalendarAlt, FaClock, FaTicketAlt, FaShieldAlt, FaMapMarkerAlt } from 'react-icons/fa'; // <<< ADDED FaMapMarkerAlt HERE

const QRCodePage = () => {
  const user = {
    name: "Jean Martin",
    event: "Cérémonie d'Ouverture", // Added event detail
    location: "Stade de France",    // Added location detail
    date: "01 mai 2024",
    hour: "14:30",
    code: "ABC123456789"
  };

  // The actual value encoded in the QR code.
  // In a real application, this would be a secure, unique token generated by the backend.
  // For demonstration, we use a concatenation.
  const qrCodeValue = `ticket_id:${user.code}|user_id:${user.name.replace(/\s/g, '')}|event:${user.event.replace(/\s/g, '')}`;

  return (
    <div className="qr-page-container">
      <header className="qr-header">
        <h1>🎉 Félicitations ! Votre billet est prêt !</h1>
        <p>Préparez-vous à vivre une expérience inoubliable aux Jeux Olympiques.</p>
      </header>

      <main className="qr-main-content">
        <section className="qr-code-section">
          <div className="qr-code-box">
            <QRCodeCanvas value={qrCodeValue} size={220} level="H" includeMargin={true} />
            <p className="qr-caption">Scannez ce QR code à l'entrée du site de l'événement.</p>
          </div>
        </section>

        <section className="ticket-details-section">
          <h2>Détails de votre billet</h2>
          <div className="ticket-info-grid">
            <div className="info-item">
              <FaUserCircle className="info-icon" />
              <p><strong>Nom :</strong> {user.name}</p>
            </div>
            <div className="info-item">
              <FaTicketAlt className="info-icon" />
              <p><strong>Événement :</strong> {user.event}</p>
            </div>
            <div className="info-item">
              <FaMapMarkerAlt className="info-icon" />
              <p><strong>Lieu :</strong> {user.location}</p>
            </div>
            <div className="info-item">
              <FaCalendarAlt className="info-icon" />
              <p><strong>Date :</strong> {user.date}</p>
            </div>
            <div className="info-item">
              <FaClock className="info-icon" />
              <p><strong>Heure :</strong> {user.hour}</p>
            </div>
            <div className="info-item">
              <FaTicketAlt className="info-icon" /> {/* Reusing FaTicketAlt for ticket code */}
              <p><strong>Code Billet :</strong> {user.code}</p>
            </div>
          </div>
        </section>

        <section className="security-banner">
          <FaShieldAlt className="security-icon" />
          <h3>Votre Sécurité, Notre Priorité</h3>
          <p>
            Ce billet est sécurisé par des clés numériques uniques et invisibles (combinaison d'une clé de création et d'une clé d'achat) pour garantir son authenticité.
            Toute reproduction non autorisée sera détectée.
          </p>
        </section>

        <section className="action-buttons">
          <button className="btn-primary">
            <FaDownload className="button-icon" /> Télécharger le billet (PDF)
          </button>
          <Link to="/" className="btn-secondary">
            <FaHome className="button-icon" /> Retour à l’accueil
          </Link>
        </section>
      </main>

      {/* Footer can be managed globally if you have a Layout component */}
      <footer className="footer">
        <p>&copy; 2024 Jeux Olympiques France. Tous droits réservés.</p>
      </footer>
    </div>
  );
};

export default QRCodePage;